using System.Text;

namespace Rivet.Core
{
    public class CMakeGenerator
    {
        public void Generate(RivetConfig config)
        {
            StringBuilder cmake = new();

            cmake.AppendLine("# Generated by Rivet");
            cmake.AppendLine();

            foreach (RivetDependency dependency in config.Packages)
            {
                cmake.AppendLine(
                    $"add_subdirectory(external/{dependency.Name})"
                );
            }

            File.WriteAllText("rivet.cmake", cmake.ToString());
        }
    }
}